### ISSUE TITLE
Dont limit the URL field width

### ISSUE THREAD

**Issue by michaelrimbach** [FacetWP/log-http-requests#1]
Hi,

thanks for the very helpful plugin!

Could you please remove the 400px width limitation from the ".widefat .field-url div" field? 
Thanks! 

![2018-05-29_11h39_43](https://user-images.githubusercontent.com/1499365/40651023-00a9fc68-6335-11e8-996e-6d6c5d85a922.png)

**Comment by mgibbs189** [comment]
@michaelrimbach Sure, thanks for the suggestion. We've just rolled out 1.0.3.
