### ISSUE TITLE
Configure cleanup() period

### ISSUE THREAD

**Issue by danielbachhuber** [FacetWP/log-http-requests#2]
I'm using Log HTTP Requests to debug production interactions with a 3rd party API.

Because I'm not able to review the logs every day, it would be useful if I could change the cleanup period from `-1 days` to a week or so.

Something you'd be open to a pull request for?

**Comment by mgibbs189** [comment]
@danielbachhuber Sure, I added a `lhr_expiration_days` hook 👍 

```php
add_filter( 'lhr_expiration_days', function( $days ) {
    return 7;
});
```

**Comment by danielbachhuber** [comment]
Great, thanks!
