### ISSUE TITLE
Suggestion: Add menu page under Tools

### ISSUE THREAD

**Issue by aaemnnosttv** [FacetWP/log-http-requests#7]
Currently the plugin adds its admin view under the general _Settings_ admin menu.

I think it may be a bit more intuitive for users to find this under the _Tools_ menu, particularly because it has no settings 😄 

I'm happy to send a PR for this if you're open to the idea. Thanks for the plugin!

**Comment by mgibbs189** [comment]
@aaemnnosttv Good call. Sure, a PR would be awesome! :)
