### ISSUE TITLE
Request: Add navigation to details modal

### ISSUE THREAD

**Issue by aaemnnosttv** [FacetWP/log-http-requests#8]
It would be nice if the user could click forward/backwards from the details view to go to the next/previous item in the log (similar to the attachment details modal). 

As part of this, the request URL would need to be added to the modal as well (something I feel would be a good addition even now), but that's the easy part 😄 

Let me know if you'd be open to a PR for this.

**Comment by mgibbs189** [comment]
@aaemnnosttv I like the idea. What are your thoughts on pagination? E.g. if the modal is showing the last result on the current page, would the "Next" button disappear or would it auto-paginate?

**Comment by aaemnnosttv** [comment]
Oh, good question. Probably whatever fits in easier the the existing infrastructure in core 😄 

I haven't looked into it much, so there would be some discovery to be done but I have worked with WP's media views a bit in the past.

**Comment by mgibbs189** [comment]
Added into `master`, closing.
